name: Deploy Frontend with Compose
on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_FRONT_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update && sudo apt-get install -y docker-compose
            sudo chmod 666 /var/run/docker.sock
            sudo rm -rf Front_Eval2
            git clone -b deploy https://github.com/ignaciokort/Front_Eval2.git
            cd Front_Eval2
            
            # Usamos la IP PRIVADA del Backend para la comunicación interna
            echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" > .env
            
            docker-compose down
            docker-compose up -d --build
