name: Deploy Frontend with Compose
on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_FRONT_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Asegurar permisos
            sudo chmod 666 /var/run/docker.sock
            
            # 2. Limpiar y clonar la rama deploy (IE4)
            sudo rm -rf Front_Eval2
            git clone -b deploy https://github.com/ignaciokort/Front_Eval2.git
            cd Front_Eval2
            
            # 3. Crear el archivo .env
            echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" > .env
            
            # 4. USAR DOCKER COMPOSE SIN EL GUION (Este es el truco)
            docker compose down
            docker compose up -d --build
